---
- name: Inatlling the mariadb server
  apt:
    name: mariadb-server
    state: present

- name: Install mysql
  apt:
    name: python3-pymysql
    state: present

- name: Start Mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  become: true

- name: Restart Mysql
  systemd:
    name: mysql
    state: restarted
    enabled: yes
  become: true
